stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - build

.build: &build_template
  variables:
    CI: "false"
  image: node:9.4.0
  stage: build
  script:
    - npm install
    - npm run build --production
  environment:
    name: $ENVIRONMENT
    url: https://${ENV_SLUG}marketplace.poetri.co

build_develop:
  variables:
    ENVIRONMENT: development
    ENV_SLUG: dev-
  <<: *build_template
  only:
    - develop

build_staging:
  variables:
    ENVIRONMENT: staging
    ENV_SLUG: staging-
  <<: *build_template
  only:
    - master

build_production:
  variables:
    ENVIRONMENT: production
    ENV_SLUG: ''
  <<: *build_template
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

## Deployment - Production
.deploy: &deploy_template
  image: napp/docker-aws-cli
  stage: deploy
  script:
    - aws s3 rm s3://$AWS_BUCKET_ID --quiet --recursive
    - aws s3 cp build s3://$AWS_BUCKET_ID/ --quiet --recursive --acl public-read
    - aws configure set preview.cloudfront true
    - "export INVALIDATION_ID=\"$(aws cloudfront create-invalidation
        --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID
        --paths '/*' | grep -oP '(?<=\\\"Id\\\": \\\").*(?=\\\")')\""
    - aws cloudfront wait invalidation-completed --id $INVALIDATION_ID
        --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID
  environment:
    name: $ENVIRONMENT
    url: https://${ENV_SLUG}marketplace.poetri.co
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

deploy_develop:
  variables:
    AWS_BUCKET_ID: $AWS_DEV_BUCKET
    AWS_CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DEV_ID
    ENVIRONMENT: development
    ENV_SLUG: dev-
  <<: *deploy_template
  only:
    - develop

deploy_staging:
  variables:
    AWS_BUCKET_ID: $AWS_STAGING_BUCKET
    AWS_CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_STAGING_ID
    ENVIRONMENT: staging
    ENV_SLUG: staging-
  <<: *deploy_template
  only:
    - master

deploy_production:
  variables:
    AWS_BUCKET_ID: $AWS_BUCKET
    AWS_CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_ID
    ENVIRONMENT: production
    ENV_SLUG: ''
  <<: *deploy_template
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/